name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:      
    - name: Checkout code
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
    #- uses: actions/checkout@v4
    - name: Build and push Docker image
      #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fb-api:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fb-api:latest
